version: '3.9'

services:
  micro-appoint-scheduler:
    depends_on:
      - mongodb
    build: .
    hostname: scheduler
    env_file:
      - .env
    image: micro-appoint-scheduler
    container_name: scheduler-backend
    networks:
      - micro-appoint-net
    ports:
      - 50054:50051
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: scheduler-db
    hostname: scheduler-db
    restart: always
    networks:
      - micro-appoint-net
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${DB_NAME}
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - micro-appoint-net
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: scheduler-db
      ME_CONFIG_MONGODB_PORT: "27017"

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local
  db-data:
    driver: local
  db-config:
    driver: local

networks:
  micro-appoint-net:
    name: micro-appoint-net
    external: true
